// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ognwbfuqkhjareqyvefk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbndiZnVxa2hqYXJlcXl2ZWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzI2NjIsImV4cCI6MjA2NDg0ODY2Mn0.gu2yX7bG0uFuKgc_TpF75WIQD7gnsi_4NpE0GPMKbOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);